### ISSUE TITLE
The mod itself having problems with jei hooks mod

### ISSUE THREAD

**Issue by OddTroTro123** [JustAHuman-xD/EasyItemList#4] opened 2024-11-10 17:36 UTC
Caused by: java.lang.IllegalAccessError: class me.justahuman.easy_item_list.hooks.JeiHook tried to access private method 'void net.minecraft.class_2960.⋖init⋗(java.lang.String, java.lang.String)' (me.justahuman.easy_item_list.hooks.JeiHook and net.minecraft.class_2960 are in unnamed module of loader 'knot' @4d49af10)
[launcher_log.txt](https://github.com/user-attachments/files/17692395/launcher_log.txt)

**Comment by JustAHuman-xD** [comment] 2024-11-10 18:53
It's caused by the Identifier constructer being made private in 1.21+ I didn't catch my usage of it so jei is broken on those newer versions until I release a version specifically for 1.21 which I will do soon, ty for reporting

**Comment by JustAHuman-xD** [comment] 2024-11-10 20:43
fixed in v0.1.4-1.20.5

**Closed as completed by JustAHuman-xD** 2024-11-10 20:43 UTC
